# Generated by Django 2.0.6 on 2018-06-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/home/samuel/projects/conversation-app/api/avatars/Avatar.jpg', upload_to='avatars'),
        ),
    ]
